import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from './lib/supabase';
import { bookmarksApi, collectionsApi, deleteAccount, login, logoutAll, metadata, preferencesApi, profileApi, register, tagsApi } from './lib/api';
import { exportHtml, exportJson, parseImportFile, type ExportPayload } from './lib/importExport';
import type { Bookmark, BookmarkTag, Collection, CollectionBookmark, Profile, Tag, UserPreferences } from './lib/types';
import { Search, Plus, Star, Clock3, Folder, Tag as TagIcon, Settings, LogOut, Command, ExternalLink, Copy, Trash2, X, Menu, Shield, ChevronRight, Upload, Download, Edit3, RefreshCw } from 'lucide-react';

type View = 'all' | 'starred' | 'recent' | 'collections' | 'tags' | 'settings';
const format = (s: string | null) => s ? new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' }).format(Math.round((new Date(s).getTime() - Date.now()) / 86400000), 'day') : '—';

function Auth({ onDone }: { onDone: () => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [uid, setUid] = useState('');
  const [pw, setPw] = useState('');
  const [confirm, setConfirm] = useState('');
  const [msg, setMsg] = useState('');
  const [busy, setBusy] = useState(false);
  const submit = async () => {
    setBusy(true); setMsg('');
    try {
      if (mode === 'register') {
        if (pw !== confirm) throw new Error('Passwords do not match.');
        if (pw.length < 8) throw new Error('Use at least 8 characters for your password.');
        const d = await register(uid, pw, confirm);
        if (d.session) { const { error } = await supabase.auth.setSession(d.session); if (error) throw error; }
        onDone();
      } else { await login(uid, pw); onDone(); }
    } catch (e: any) { setMsg(e.message || 'Request failed.'); }
    finally { setBusy(false); }
  };
  return <div className="auth"><div className="auth-grid"/><div className="auth-card">
    <div className="brand"><span className="brand-mark">N</span><span>NEXUS</span></div>
    <p className="eyebrow">PERSONAL COMMAND CENTER</p>
    <h1>{mode === 'login' ? 'Enter the vault' : 'Create your vault'}</h1>
    <p className="muted">{mode === 'login' ? 'Sign in with your User ID and password.' : 'Choose your own User ID and password. NEXUS does not collect email.'}</p>
    <input className="input" placeholder="User ID" autoCapitalize="none" value={uid} onChange={e => setUid(e.target.value.toLowerCase())} autoComplete="username" />
    <input className="input" type="password" placeholder="Password" value={pw} onChange={e => setPw(e.target.value)} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} />
    {mode === 'register' && <input className="input" type="password" placeholder="Confirm password" value={confirm} onChange={e => setConfirm(e.target.value)} autoComplete="new-password" />}
    <button className="primary wide" disabled={busy} onClick={submit}>{busy ? 'Processing…' : mode === 'login' ? 'Access NEXUS' : 'Create account'}</button>
    {msg && <div className="notice">{msg}</div>}
    <div className="auth-links">{mode === 'login' ? <button onClick={() => {setMode('register');setMsg('')}}>Create account</button> : <button onClick={() => {setMode('login');setMsg('')}}>Back to login</button>}</div>
    {mode === 'register' && <div className="security-note"><Shield size={15}/> Password recovery is not available. If you forget it, create a new account.</div>}
    {mode === 'login' && <div className="security-note"><Shield size={15}/> Your data is isolated with Supabase Row Level Security.</div>}
  </div></div>;
}

export function App() {
  const [session, setSession] = useState<any>(null); const [loading, setLoading] = useState(true);
  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false); });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, s) => { setSession(s); });
    return () => subscription.unsubscribe();
  }, []);
  if (loading) return <div className="boot">NEXUS<span>INITIALIZING</span></div>;
  return session ? <Vault /> : <Auth onDone={() => undefined} />;
}

function Vault() {
  const [view, setView] = useState<View>('all'); const [bookmarks, setBookmarks] = useState<Bookmark[]>([]); const [collections, setCollections] = useState<Collection[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [bookmarkTags, setBookmarkTags] = useState<BookmarkTag[]>([]); const [collectionLinks, setCollectionLinks] = useState<CollectionBookmark[]>([]); const [profile, setProfile] = useState<Profile | null>(null); const [preferences, setPreferences] = useState<UserPreferences | null>(null); const [query, setQuery] = useState(''); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Bookmark | null>(null); const [cmd, setCmd] = useState(false); const [mobile, setMobile] = useState(false); const [selected, setSelected] = useState<Bookmark | null>(null); const fileRef = useRef<HTMLInputElement>(null);
  const load = async () => { try { const [b, c, t, p, bt, cb, prefs] = await Promise.all([bookmarksApi.list(), collectionsApi.list(), tagsApi.list(), profileApi.get(), tagsApi.links(), collectionsApi.links(), preferencesApi.get()]); setBookmarks(b); setCollections(c); setTags(t); setProfile(p); setBookmarkTags(bt as BookmarkTag[]); setCollectionLinks(cb as CollectionBookmark[]); setPreferences(prefs); } catch (e) { console.error(e); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { const h = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); setCmd(v => !v); } if (e.key === 'Escape') { setCmd(false); setModal(false); setEditing(null); setSelected(null); } }; window.addEventListener('keydown', h); return () => window.removeEventListener('keydown', h); }, []);
  const collectionNames = useMemo(() => new Map(collections.map(c => [c.id, c.name])), [collections]); const tagNames = useMemo(() => new Map(tags.map(t => [t.id, t.name])), [tags]);
  const filtered = useMemo(() => bookmarks.filter(b => { if (view === 'starred' && !b.is_favorite) return false; if (view === 'recent' && new Date(b.created_at).getTime() < Date.now() - 7 * 864e5) return false; const linkedCollection = collectionLinks.filter(x => x.bookmark_id === b.id).map(x => collectionNames.get(x.collection_id) || '').join(' '); const linkedTags = bookmarkTags.filter(x => x.bookmark_id === b.id).map(x => tagNames.get(x.tag_id) || '').join(' '); const q = query.toLowerCase().trim(); return !q || [b.title,b.url,b.domain,b.description,b.notes,linkedCollection,linkedTags].filter(Boolean).some(x => String(x).toLowerCase().includes(q)); }), [bookmarks, query, view, bookmarkTags, collectionLinks, collectionNames, tagNames]);
  const logout = async () => { await supabase.auth.signOut(); }; const openImport = () => fileRef.current?.click();
  const importFile = async (file: File) => { try { const data = await parseImportFile(file); const imported = (data.bookmarks || []) as any[]; for (const b of imported) { if (!b.url) continue; const created = await bookmarksApi.create({ url: b.url, title: b.title || null, description: b.description || null, notes: b.notes || null, favicon_url: b.favicon_url || null, image_url: b.image_url || null, is_favorite: !!b.is_favorite, domain: b.domain || null }); const collection = (data.collections || []).find((c: any) => (data.collection_bookmarks || []).some((l: any) => l.bookmark_id === b.id && l.collection_id === c.id)); if (collection) { const existing = collections.find(c => c.name.toLowerCase() === String(collection.name).toLowerCase()); const c = existing || await collectionsApi.create({ name: collection.name, description: collection.description || null, icon: collection.icon || null }); await collectionsApi.addBookmark(c.id, created.id); } } await load(); alert('Import complete.'); } catch (e: any) { alert(e.message || 'Unable to import bookmarks.'); } finally { if (fileRef.current) fileRef.current.value = ''; } };
  const payload: ExportPayload = { version: 1, exported_at: new Date().toISOString(), bookmarks, collections, tags, bookmark_tags: bookmarkTags, collection_bookmarks: collectionLinks };
  const nav = (v: View) => { setView(v); setMobile(false); setCmd(false); };
  return <div className="app"><aside className={mobile ? 'sidebar mobile-open' : 'sidebar'}><div className="side-brand"><span className="brand-mark">N</span><b>NEXUS</b><button className="icon-btn mobile-close" onClick={() => setMobile(false)}><X size={18}/></button></div><nav>{[['all','All Bookmarks',Search],['starred','Starred',Star],['recent','Recent',Clock3],['collections','Collections',Folder],['tags','Tags',TagIcon],['settings','Settings',Settings]].map(([k,label,Icon]: any)=><button key={k} className={view===k?'nav-item active':'nav-item'} onClick={() => nav(k)}><Icon size={17}/><span>{label}</span>{k==='all'&&<small>{bookmarks.length}</small>}</button>)}</nav><div className="side-account"><div className="avatar">{profile?.user_id?.slice(0,1).toUpperCase()||'N'}</div><div><b>{profile?.user_id||'NEXUS USER'}</b><span>Personal vault</span></div><button className="icon-btn" onClick={logout}><LogOut size={16}/></button></div></aside>
  <main className="main"><header className="topbar"><button className="icon-btn mobile-menu" onClick={() => setMobile(true)}><Menu size={19}/></button><div className="search"><Search size={17}/><input aria-label="Search your vault" placeholder="Search your vault…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="command" onClick={()=>setCmd(true)}><Command size={16}/><span>Command</span><kbd>⌘K</kbd></button><button className="primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={17}/> <span>Add bookmark</span></button></header>
  <section className="content"><div className="heading"><div><p className="eyebrow">{view==='all'?'VAULT OVERVIEW':view.toUpperCase()}</p><h2>{view==='all'?'Recent signals':view==='starred'?'Starred signals':view==='recent'?'Recent signals':view==='collections'?'Collections':view==='tags'?'Tags':'System settings'}</h2></div><span className="signal">● SYSTEM ONLINE</span></div>
  {view==='settings'?<SettingsPanel profile={profile} preferences={preferences} onPreferences={setPreferences} onLogout={logout} onImport={openImport} onExportJson={()=>exportJson(payload)} onExportHtml={()=>exportHtml(bookmarks)} onLogoutAll={async()=>{await logoutAll(); await logout();}} onDelete={async()=>{if(confirm('Delete your NEXUS account and all vault data? This cannot be undone.')){await deleteAccount();await logout();}}}/>:view==='collections'?<CollectionPanel collections={collections} onCreate={async()=>{const name=prompt('Collection name');if(name?.trim()){try{await collectionsApi.create({name:name.trim()});await load()}catch(e:any){alert(e.message)}}}} onRefresh={load}/>:view==='tags'?<TagPanel tags={tags} onRefresh={load}/>:<><Stats bookmarks={bookmarks} collections={collections} tags={tags}/><div className="section-title"><span>{query?`Search results for “${query}”`:'Recent signals'}</span><span className="muted">{filtered.length} items</span></div><div className="bookmark-grid">{filtered.map(b=><BookmarkCard key={b.id} b={b} tags={bookmarkTags.filter(x=>x.bookmark_id===b.id).map(x=>tagNames.get(x.tag_id)).filter(Boolean) as string[]} collection={collectionLinks.find(x=>x.bookmark_id===b.id)?.collection_id ? collectionNames.get(collectionLinks.find(x=>x.bookmark_id===b.id)!.collection_id) : undefined} onOpen={async()=>{await bookmarksApi.open(b.id);window.open(b.url,'_blank','noopener,noreferrer');}} onFavorite={async()=>{const x=await bookmarksApi.update(b.id,{is_favorite:!b.is_favorite});setBookmarks(v=>v.map(z=>z.id===x.id?x:z))}} onDelete={async()=>{if(confirm('Delete this bookmark?')){await bookmarksApi.remove(b.id);setBookmarks(v=>v.filter(z=>z.id!==b.id))}}} onEdit={()=>{setEditing(b);setModal(true)}} onSelect={()=>setSelected(b)}/>)}</div>{filtered.length===0&&<div className="empty"><div className="empty-icon">⌁</div><h3>{query?'No matching signals found.':'Your vault is empty.'}</h3><p>{query?'Try another search term.':'Add your first bookmark to begin building your digital vault.'}</p>{!query&&<button className="primary" onClick={()=>setModal(true)}><Plus size={16}/> Add first bookmark</button>}</div>}</>}</section></main>
  <div className="mobile-nav">{[['all','Vault',Search],['starred','Starred',Star],['collections','Collections',Folder],['settings','Settings',Settings]].map(([k,label,Icon]:any)=><button className={view===k?'active':''} key={k} onClick={()=>nav(k)}><Icon size={17}/><span>{label}</span></button>)}</div>
  <input ref={fileRef} hidden type="file" accept=".json,.html,text/html,application/json" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/>
  {modal&&<BookmarkModal bookmark={editing} collections={collections} tags={tags} links={bookmarkTags} collectionLinks={collectionLinks} onClose={()=>{setModal(false);setEditing(null)}} onCreated={async()=>{setModal(false);setEditing(null);await load()}}/>}{selected&&<Detail b={selected} tags={bookmarkTags.filter(x=>x.bookmark_id===selected.id).map(x=>tagNames.get(x.tag_id)).filter(Boolean) as string[]} collection={collectionLinks.find(x=>x.bookmark_id===selected.id)?.collection_id ? collectionNames.get(collectionLinks.find(x=>x.bookmark_id===selected.id)!.collection_id) : undefined} onClose={()=>setSelected(null)} onEdit={()=>{setSelected(null);setEditing(selected);setModal(true)}}/>}{cmd&&<CommandPalette close={()=>setCmd(false)} add={()=>{setCmd(false);setModal(true)}} nav={nav} logout={logout} createCollection={()=>{setCmd(false);nav('collections')}} importBookmarks={openImport} exportBookmarks={()=>exportJson(payload)}/>}</div>;
}

function Stats({bookmarks,collections,tags}:{bookmarks:Bookmark[];collections:Collection[];tags:Tag[]}){return <div className="stats"><div><span>BOOKMARKS</span><strong>{bookmarks.length}</strong></div><div><span>STARRED</span><strong>{bookmarks.filter(x=>x.is_favorite).length}</strong></div><div><span>COLLECTIONS</span><strong>{collections.length}</strong></div><div><span>TAGS</span><strong>{tags.length}</strong></div></div>}

function BookmarkCard({b,tags,collection,onOpen,onFavorite,onDelete,onEdit,onSelect}:{b:Bookmark;tags:string[];collection?:string;onOpen:()=>void;onFavorite:()=>void;onDelete:()=>void;onEdit:()=>void;onSelect:()=>void}){return <article className="card" onClick={onSelect}><div className="card-top"><div className="favicon">{b.domain?.slice(0,1).toUpperCase()||'↗'}</div><button aria-label="Favorite" className={b.is_favorite?'star active':'star'} onClick={e=>{e.stopPropagation();onFavorite()}}><Star size={17} fill={b.is_favorite?'currentColor':'none'}/></button></div><h3>{b.title||b.url}</h3><div className="domain">{b.domain||b.url}</div>{b.description&&<p>{b.description}</p>}<div className="chips">{collection&&<span>⌂ {collection}</span>}{tags.slice(0,3).map(t=><span key={t}>#{t}</span>)}</div><div className="card-foot"><span>{format(b.last_opened_at || b.created_at)}</span><div><button className="mini" onClick={e=>{e.stopPropagation();onEdit()}} title="Edit"><Edit3 size={14}/></button><button className="mini" onClick={e=>{e.stopPropagation();navigator.clipboard?.writeText(b.url)}} title="Copy URL"><Copy size={14}/></button><button className="mini" onClick={e=>{e.stopPropagation();onOpen()}} title="Open"><ExternalLink size={14}/></button><button className="mini danger" onClick={e=>{e.stopPropagation();onDelete()}} title="Delete"><Trash2 size={14}/></button></div></div></article>}

function BookmarkModal({bookmark,collections,tags,links,collectionLinks,onClose,onCreated}:{bookmark:Bookmark|null;collections:Collection[];tags:Tag[];links:BookmarkTag[];collectionLinks:CollectionBookmark[];onClose:()=>void;onCreated:()=>void}){
  const [url,setUrl]=useState(bookmark?.url||'');const [title,setTitle]=useState(bookmark?.title||'');const [description,setDescription]=useState(bookmark?.description||'');const [notes,setNotes]=useState(bookmark?.notes||'');const [favorite,setFavorite]=useState(bookmark?.is_favorite||false);const [collectionId,setCollectionId]=useState(collectionLinks.find(x=>x.bookmark_id===bookmark?.id)?.collection_id||'');const [selectedTags,setSelectedTags]=useState<string[]>(links.filter(x=>x.bookmark_id===bookmark?.id).map(x=>x.tag_id));const [busy,setBusy]=useState(false);const [metaBusy,setMetaBusy]=useState(false);const fetchMeta=async()=>{if(!url)return;setMetaBusy(true);try{const m=await metadata(url);setTitle(m.title||'');setDescription(m.description||'');}catch(e:any){alert(e.message||'Unable to fetch page metadata.')}finally{setMetaBusy(false)}};
  const save=async()=>{setBusy(true);try{let saved:Bookmark;if(bookmark)saved=await bookmarksApi.update(bookmark.id,{url,title:title||null,description:description||null,notes:notes||null,is_favorite:favorite,domain: (()=>{try{return new URL(url).hostname}catch{return null}})()});else saved=await bookmarksApi.create({url,title:title||null,description:description||null,notes:notes||null,is_favorite:favorite});const oldTags=links.filter(x=>x.bookmark_id===saved.id).map(x=>x.tag_id);for(const id of oldTags.filter(id=>!selectedTags.includes(id)))await tagsApi.detach(saved.id,id);for(const id of selectedTags.filter(id=>!oldTags.includes(id)))await tagsApi.attach(saved.id,id);const oldCollection=collectionLinks.find(x=>x.bookmark_id===saved.id)?.collection_id;if(oldCollection&&oldCollection!==collectionId)await collectionsApi.removeBookmark(oldCollection,saved.id);if(collectionId&&oldCollection!==collectionId)await collectionsApi.addBookmark(collectionId,saved.id);onCreated()}catch(e:any){alert(e.message||'Unable to save bookmark.')}finally{setBusy(false)}};
  return <div className="overlay"><div className="modal"><div className="modal-head"><div><p className="eyebrow">{bookmark?'EDIT SIGNAL':'NEW SIGNAL'}</p><h2>{bookmark?'Edit bookmark':'Add bookmark'}</h2></div><button className="icon-btn" onClick={onClose}><X size={19}/></button></div><label>URL<div className="url-row"><input className="input" placeholder="https://example.com" value={url} onChange={e=>setUrl(e.target.value)}/><button className="secondary" disabled={metaBusy} onClick={fetchMeta}>{metaBusy?'Fetching…':'Fetch metadata'}</button></div></label><label>Title<input className="input" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea className="input" rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Notes<textarea className="input" rows={2} placeholder="Private notes…" value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Collection<select className="input" value={collectionId} onChange={e=>setCollectionId(e.target.value)}><option value="">No collection</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tags<div className="tag-select">{tags.map(t=><button type="button" className={selectedTags.includes(t.id)?'tag-choice active':'tag-choice'} key={t.id} onClick={()=>setSelectedTags(v=>v.includes(t.id)?v.filter(x=>x!==t.id):[...v,t.id])}>#{t.name}</button>)}</div></label><label className="check"><input type="checkbox" checked={favorite} onChange={e=>setFavorite(e.target.checked)}/> Mark as favorite</label><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!url} onClick={save}>{busy?'Saving…':bookmark?'Save changes':'Save bookmark'}</button></div></div></div>;
}

function Detail({b,tags,collection,onClose,onEdit}:{b:Bookmark;tags:string[];collection?:string;onClose:()=>void;onEdit:()=>void}){return <div className="detail"><button className="icon-btn" onClick={onClose}><X size={18}/></button><button className="secondary detail-edit" onClick={onEdit}><Edit3 size={14}/> Edit</button><div className="detail-icon">{b.domain?.slice(0,1).toUpperCase()||'N'}</div><p className="eyebrow">SIGNAL DETAIL</p><h2>{b.title||b.url}</h2><a href={b.url} target="_blank" rel="noreferrer">{b.url}</a>{b.description&&<p>{b.description}</p>}{collection&&<div className="chips"><span>⌂ {collection}</span></div>}{tags.length>0&&<div className="chips">{tags.map(t=><span key={t}>#{t}</span>)}</div>}<div className="detail-meta"><span>Added {new Date(b.created_at).toLocaleString()}</span><span>Opened {format(b.last_opened_at)}</span></div>{b.notes&&<div className="note"><b>Private note</b><p>{b.notes}</p></div>}</div>}

function CommandPalette({close,add,nav,logout,createCollection,importBookmarks,exportBookmarks}:any){const commands=[['Add bookmark',add,Plus],['Search bookmarks',()=>{close();nav('all')},Search],['Open starred',()=>{close();nav('starred')},Star],['Open recent',()=>{close();nav('recent')},Clock3],['Create collection',createCollection,Folder],['Import bookmarks',importBookmarks,Upload],['Export bookmarks',exportBookmarks,Download],['Settings',()=>{close();nav('settings')},Settings],['Logout',logout,LogOut]];return <div className="overlay"><div className="cmd-palette"><div className="cmd-search"><Command size={17}/><input autoFocus placeholder="Type a command…"/></div>{commands.map(([label,fn,Icon]:any)=><button key={label} className="cmd-item" onClick={fn}><Icon size={17}/><span>{label}</span><ChevronRight size={14}/></button>)}</div><button className="scrim" onClick={close}/></div>}

function CollectionPanel({collections,onCreate,onRefresh}:{collections:Collection[];onCreate:()=>void;onRefresh:()=>void}){const edit=async(c:Collection)=>{const name=prompt('Collection name',c.name);if(name?.trim()&&name!==c.name){try{await collectionsApi.update(c.id,{name:name.trim()});onRefresh()}catch(e:any){alert(e.message)}}};const remove=async(c:Collection)=>{if(confirm(`Delete collection “${c.name}”? Bookmarks will remain.`)){await collectionsApi.remove(c.id);onRefresh()}};return <div><div className="panel-actions"><button className="primary" onClick={onCreate}><Plus size={16}/> New collection</button></div><div className="collection-grid">{collections.map(c=><div className="collection-card" key={c.id}><Folder size={20}/><b>{c.name}</b><span>{c.description||'Personal collection'}</span><div className="card-actions"><button className="mini" onClick={()=>edit(c)}><Edit3 size={14}/></button><button className="mini danger" onClick={()=>remove(c)}><Trash2 size={14}/></button></div></div>)}</div>{!collections.length&&<div className="empty"><div className="empty-icon"><Folder/></div><h3>Create your first collection.</h3></div>}</div>}

function TagPanel({tags,onRefresh}:{tags:Tag[];onRefresh:()=>void}){const create=async()=>{const name=prompt('Tag name');if(name?.trim()){try{await tagsApi.create(name);onRefresh()}catch(e:any){alert(e.message)}}};const edit=async(t:Tag)=>{const name=prompt('Tag name',t.name);if(name?.trim()&&name!==t.name){try{await tagsApi.update(t.id,name);onRefresh()}catch(e:any){alert(e.message)}}};const remove=async(t:Tag)=>{if(confirm(`Delete #${t.name}?`)){await tagsApi.remove(t.id);onRefresh()}};return <div><div className="panel-actions"><button className="primary" onClick={create}><Plus size={16}/> New tag</button></div><div className="tag-cloud">{tags.map(t=><span className="tag-item" key={t.id}>#{t.name}<button onClick={()=>edit(t)}><Edit3 size={12}/></button><button onClick={()=>remove(t)}><Trash2 size={12}/></button></span>)}</div>{!tags.length&&<div className="empty"><div className="empty-icon"><TagIcon/></div><h3>No tags yet.</h3></div>}</div>}

function SettingsPanel({profile,preferences,onPreferences,onLogout,onImport,onExportJson,onExportHtml,onLogoutAll,onDelete}:{profile:Profile|null;preferences:UserPreferences|null;onPreferences:(p:UserPreferences)=>void;onLogout:()=>void;onImport:()=>void;onExportJson:()=>void;onExportHtml:()=>void;onLogoutAll:()=>Promise<void>;onDelete:()=>Promise<void>}){
  const save=async(changes:Partial<UserPreferences>)=>{try{const p=await preferencesApi.update(changes);onPreferences(p)}catch(e:any){alert(e.message||'Unable to save customization.')}};
  const reset=async()=>{try{const p=await preferencesApi.reset();onPreferences(p)}catch(e:any){alert(e.message||'Unable to reset customization.')}};
  if(!preferences)return <div className="settings-panel"><div className="setting"><b>Loading customization…</b></div></div>;
  return <div className="settings-panel">
    <div className="setting"><div><b>Account</b><span>User ID: {profile?.user_id||'—'}</span><span>Email is not collected or displayed by NEXUS.</span></div></div>
    <div className="setting"><div><b>Customization</b><span>Preferences are stored privately for your account.</span></div><div className="setting-actions settings-controls">
      <label>Theme<select className="input" value={preferences.theme} onChange={e=>save({theme:e.target.value})}><option value="dark">Dark</option><option value="light">Light</option><option value="system">System</option></select></label>
      <label>Accent<select className="input" value={preferences.accent_color} onChange={e=>save({accent_color:e.target.value})}><option value="cyan">Cyan</option><option value="violet">Violet</option><option value="pink">Pink</option><option value="lime">Lime</option></select></label>
      <label>Density<select className="input" value={preferences.density} onChange={e=>save({density:e.target.value})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option><option value="spacious">Spacious</option></select></label>
      <label>Background<select className="input" value={preferences.background_style} onChange={e=>save({background_style:e.target.value})}><option value="grid">Grid</option><option value="plain">Plain</option><option value="aurora">Aurora</option></select></label>
      <label>Glow<select className="input" value={preferences.glow_intensity} onChange={e=>save({glow_intensity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>
      <label>Border<select className="input" value={preferences.border_intensity} onChange={e=>save({border_intensity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>
      <label>Sidebar<select className="input" value={preferences.sidebar_mode} onChange={e=>save({sidebar_mode:e.target.value})}><option value="expanded">Expanded</option><option value="compact">Compact</option></select></label>
      <label>Bookmarks<select className="input" value={preferences.bookmark_view} onChange={e=>save({bookmark_view:e.target.value})}><option value="grid">Grid</option><option value="list">List</option></select></label>
      <label className="check"><input type="checkbox" checked={preferences.reduced_motion} onChange={e=>save({reduced_motion:e.target.checked})}/> Reduced motion</label>
      <button className="secondary" onClick={reset}>Reset customization</button>
    </div></div>
    <div className="setting"><div><b>Data</b><span>Export your bookmarks, collections, tags and metadata. Imports never contain authentication secrets.</span></div><div className="setting-actions"><button className="secondary" onClick={onExportJson}><Download size={14}/> JSON</button><button className="secondary" onClick={onExportHtml}><Download size={14}/> HTML</button><button className="secondary" onClick={onImport}><Upload size={14}/> Import</button></div></div>
    <div className="setting"><div><b>Security</b><span>Authentication is managed by Supabase Auth.</span><span>Data access is enforced with PostgreSQL RLS.</span><span>Password recovery is intentionally unavailable.</span></div><div className="setting-actions"><button className="secondary" onClick={async()=>{await onLogoutAll();}}><RefreshCw size={14}/> Logout all sessions</button><button className="secondary" onClick={onLogout}><LogOut size={14}/> Logout</button></div></div>
    <div className="setting danger-box"><div><b>Danger zone</b><span>Delete your account and all associated vault data. This cannot be undone.</span></div><button className="secondary danger-button" onClick={onDelete}><Trash2 size={14}/> Delete account</button></div>
  </div>
}
